config/routes.rb
Moviez::Application.routes.draw do
  root :to => 'movies#index'
  get '/search' => 'movies#search'
  get '/show_search_result' => 'movies#show_search_result'
  post '/movies/favorite' => 'movies#rate'
  resources :movies
  #create
  #update
  #destroy
  #read
  #show

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :title, :year, :mpaa_rating, :plot
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController


  def index
    @movies = Movie.all
  end

  def search
    @search_result = Imdb::Search.new(params[:title].to_s)
  end

  def show_search_result
    @movie = movie_search(params[:id])
  end

  def create

    movie = movie_search(params[:id])
    movie = Movie.new(
      :title => movie.title,
      :year => movie.year,
      :mpaa_rating => movie.mpaa_rating,
      :plot => movie.plot)
    if params[:x] == "Favorite"
      movie.rating = 100
    end
      movie.save
      redirect_to '/movies'
  end

  def rate
    id = params[:id]
    @movie = Movie.find(id)
    if params[:rate] == "plus"
      @movie.rating += 1
    else
      @movie.rating -= 1
    end
      movie.save
      redirect '/movies'
  end

  def new
  end

  def edit
  end

  def show
    id = params[:id]
    @movie = Movie.find(id)

  end

  def update
  end

  def destroy
  end

  private
  def movie_search(id)
    Imdb::Movie.new(id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/Movies/_rating.html.erb
<%= @movie.title %></br>
<%= @movie.year %></br>
<%= @movie.mpaa_rating %> </br>
<%= @movie.rating %> </br>

<form action="/movies/favorite/<%= @movie.id%>" method="POST">
<button name ="rate" value="plus"> + </button>

</form>


<form action="/movies/favorite/<%= @movie.id %>" method="POST">
<button name="rate" value="minus"> - </button>

</form>

app/views/Movies/_searchbox.html.erb
<h2> Search Movies</h2>
<form action='/search' method='get'>
<input type="text" name="title" placeholder="search">
<button> Search </button>
</form>

app/views/Movies/create.html.erb
<%= render :partial => "rating" %>

app/views/Movies/favorite.html.erb
<%= @movie.title %></br>
<%= @movie.year %></br>
<%= @movie.mpaa_rating %></br>
<%= @movie.plot %></br>

app/views/Movies/index.html.erb
<h1> These are your movies </h1><br/>
<ul>
<% @movies.each do |movie| %>
<li>
<a href="/movies/<%= movie.id %>"><%= movie.title %></a>


</li>
<% end %>
</ul>

<%= render :partial => "searchbox" %>

<!--<#%= link_to movie.title, movie_path(:id => movie.id) %>>

app/views/Movies/search.html.erb
<h1> Here are your search results </h1>
<ul>
<% @search_result.movies.each do |movie| %>
<li>
<%= link_to movie.title,show_search_result_path(:id => movie.id) %>
</li>
<% end %>
</ul>

app/views/Movies/show.html.erb
<h1> <%= @movie.title %>,<%= @movie.year %> </h1>
<h1> Rating: <%= @movie.rating %> </h1>
<h1> MPAA Rating: <%= @movie.mpaa_rating %> </h1>

<%= render :partial => "rating" %>

app/views/Movies/show_search_result.html.erb
<h1> <%= @movie.title %>,<%= @movie.year %> </h1>
<h1> Rating: <%= @movie.rating %> </h1>
<h1> MPAA Rating: <%= @movie.mpaa_rating %> </h1>
<%= image_tag @movie.poster %>




<form action="/movies" method="POST">
<button> Favorite This Movie </button>
<input type="hidden" name="id" value="<%=@movie.id %>" >
<input type="hidden" name="x" value="Favorite">
</form>

<form action='/movies' method="POST">
<button> Save </button>
<input type="hidden" name="id" value="<%=@movie.id %>"

<input type="hidden" name="x" value="Save">

</form>
<%= render :partial => "rating" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Moviez</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>